services:
  application:
    build:
      context: .
      dockerfile: ./php/DockerFile
    image: application
    container_name: application
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel_app

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_app

  mysql:
    image: mysql
    restart: always
    container_name: mysql
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    networks:
      - laravel_app

networks:
  laravel_app:
    driver: bridge